library(assertthat)
library(plyr)
library(mvtnorm)
source('~/Documents/GitHub/mashr-zou/R/compute_covs.R')
source('~/Documents/GitHub/mashr-zou/R/cov_udi.R')
source('~/Documents/GitHub/mashr-zou/R/data2cov.R')
source('~/Documents/GitHub/mashr-zou/R/ed.R')
source('~/Documents/GitHub/mashr-zou/R/est_cor.R')
source('~/Documents/GitHub/mashr-zou/R/get_functions.R')
source('~/Documents/GitHub/mashr-zou/R/likelihoods_origdata.R')
source('~/Documents/GitHub/mashr-zou/R/likelihoods_scaleddata.R')
source('~/Documents/GitHub/mashr-zou/R/mash.R')
source('~/Documents/GitHub/mashr-zou/R/opt.R')
source('~/Documents/GitHub/mashr-zou/R/plots.R')
source('~/Documents/GitHub/mashr-zou/R/posterior.R')
source('~/Documents/GitHub/mashr-zou/R/posterior_common_cov.R')
source('~/Documents/GitHub/mashr-zou/R/posterior_lowmem.R')
source('~/Documents/GitHub/mashr-zou/R/RcppExports.R')
source('~/Documents/GitHub/mashr-zou/R/set_data.R')
source('~/Documents/GitHub/mashr-zou/R/posterior_common_cov_rec.R')
source('~/Documents/GitHub/mashr-zou/R/posterior_lowmem_rec.R')


